# configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = aluno
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/alunodb

# desabilitar o docker 
quarkus.devservices.enabled=false

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

%dev.quarkus.datasource.dev-ui.allow-sql=true

quarkus.http.auth.proactive=false

# JWT Configuration - SmallRye
mp.jwt.verify.issuer=sga-api
mp.jwt.verify.publickey.location=resources/public.pem
mp.jwt.verify.publickey.algorithm=RS256
mp.jwt.verify.groups.path=groups
mp.jwt.token.header=Authorization
mp.jwt.token.cookie=
smallrye.jwt.sign.key.location=resources/private.pem
smallrye.jwt.sign.key.algorithm=RS256

# Security Configuration
quarkus.security.jaxrs.deny-unannotated-endpoints=true

# OpenAPI - Swagger JWT Support
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=JWT
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer
